version: "3.7"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - PEERPREP_ENV=${PEERPREP_ENV:-production}
    ports:
      - "5173:5173"
    environment:
      - PEERPREP_ENV=${PEERPREP_ENV:-production}
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - user-service
  question-service:
    build:
      context: ./src/question-service
      dockerfile: Dockerfile
      args:
        - PEERPREP_ENV=${PEERPREP_ENV:-production}
    ports:
      - "3000:3000"
    environment:
      - PEERPREP_ENV=${PEERPREP_ENV:-production}
    volumes:
      - ./src/question-service:/app
    depends_on:
      - user-service
  user-service:
    build:
      context: ./src/user-service
      dockerfile: Dockerfile
      args:
        - PEERPREP_ENV=${PEERPREP_ENV:-production}
    ports:
      - "8000:8000"
    environment:
      - PEERPREP_ENV=${PEERPREP_ENV:-production}
    volumes:
      - ./src/user-service:/app
      - /app/node_modules
  matching-service:
    build:
      context: ./src/matching-service
      dockerfile: Dockerfile
      args:
        - PEERPREP_ENV=${PEERPREP_ENV:-production}
    ports:
      - "5001:5001"
    environment:
      - PEERPREP_ENV=${PEERPREP_ENV:-production}
    volumes:
      - ./src/matching-service:/app
