apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-container
          image: gcr.io/ay2324s1-cs3219-g43/client:1.0-SNAPSHOT
          ports:
            - containerPort: 5173
          env:
            - name: PEERPREP_ENV
              value: production
            - name: VITE_USER_BASE_PATH
              value: http://34.87.120.150:30000/api
            - name: VITE_QUESTION_BASE_PATH
              value: http://34.87.120.150:31000/api/questions
            - name: VITE_MATCHING_ENDPOINT
              value: http://34.87.120.150:32000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-container
          image: gcr.io/ay2324s1-cs3219-g43/user-service:1.0-SNAPSHOT
          ports:
            - containerPort: 8000
          env:
            - name: PEERPREP_ENV
              value: production
            - name: PORT
              value: "8000"
            - name: PSQL_HOST
              value: rain.db.elephantsql.com
            - name: PSQL_PASSWORD
              value: 6VxB3a2Z28_bVdbdqM5Rp1yBfALxy2KZ
            - name: PSQL_USER
              value: lcvbizby
            - name: PSQL_DATABASE
              value: lcvbizby
            - name: ACCESS_TOKEN_SECRET
              value: f98a32dcd04ff509254e8a71183503a5090626c5164aa5904ee3f243e9d64b201d005dbe4a2de932d3ea71ec724a9214bfc7ae90ca6f81dbe935e03ac3500a13
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service-container
          image: gcr.io/ay2324s1-cs3219-g43/question-service:1.0-SNAPSHOT
          ports:
            - containerPort: 3000
          env:
            - name: PEERPREP_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "mongodb+srv://group43:hioEhOo1o2t67bhX@peerprep.69rbrct.mongodb.net/question-service"
            - name: USER_BASE_PATH
              value: http://34.87.120.150:30000/api
---
apiVersion: v1
kind: Service
metadata:
  name: question-service-service
spec:
  type: NodePort
  selector:
    app: question-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service-container
          image: gcr.io/ay2324s1-cs3219-g43/matching-service:1.0-SNAPSHOT
          ports:
            - containerPort: 5001
          env:
            - name: PEERPREP_ENV
              value: production
            - name: PORT
              value: "5001"
            - name: AMPQ_HOST
              value: amqps://wevlszxo:WBogrJvrldUmrCPHfD7tETFVK7pdCIjj@armadillo.rmq.cloudamqp.com/wevlszxo
---
apiVersion: v1
kind: Service
metadata:
  name: matching-service-service
spec:
  type: NodePort
  selector:
    app: matching-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 32000
